alter table ante_core.app_usage_events drop constraint if exists app_usage_events_event_name_check;
alter table ante_core.app_usage_events add constraint app_usage_events_event_name_check check (event_name in ('today_opened','activity_opened','month_opened','history_opened','own_profile_opened','own_block_profile_opened','other_profile_opened','mvp_card_opened','bloc_month_opened','settings_opened','comment_composer_opened','reaction_picker_opened','bloc_stream_opened','share_month_clicked','monthly_summary_card_clicked'));

create or replace function public.record_ante_core_usage_event(p_auth_user_id text,p_event_name text,p_occurred_at timestamptz default now()) returns void language plpgsql security definer set search_path=ante_core,public as $$ declare v_profile_id uuid; v_event text:=trim(coalesce(p_event_name,'')); begin if v_event not in ('today_opened','activity_opened','month_opened','history_opened','own_profile_opened','own_block_profile_opened','other_profile_opened','mvp_card_opened','bloc_month_opened','settings_opened','comment_composer_opened','reaction_picker_opened','bloc_stream_opened','share_month_clicked','monthly_summary_card_clicked') then return; end if; select id into v_profile_id from ante_core.profiles where auth_user_id=trim(p_auth_user_id)::uuid; if v_profile_id is null then return; end if; insert into ante_core.app_usage_events(profile_id,event_name,occurred_at) values(v_profile_id,v_event,coalesce(p_occurred_at,now())); end; $$;

create or replace function public.read_ante_core_founder_dashboard_monthly_actions(p_now timestamptz default now()) returns jsonb language plpgsql security definer set search_path=ante_core,public as $$ declare v_start timestamptz:=date_trunc('month',coalesce(p_now,now()) at time zone 'Europe/Oslo') at time zone 'Europe/Oslo'; v_events jsonb; begin select jsonb_object_agg(event_name,jsonb_build_object('monthly',jsonb_build_object('users',users,'total',total))) into v_events from (select n.event_name,count(distinct e.profile_id) filter(where e.occurred_at>=v_start) users,count(e.id) filter(where e.occurred_at>=v_start) total from (values('share_month_clicked'),('monthly_summary_card_clicked')) n(event_name) left join ante_core.app_usage_events e on e.event_name=n.event_name group by n.event_name) x; return jsonb_build_object('events',coalesce(v_events,'{}'::jsonb)); end; $$;
revoke execute on function public.record_ante_core_usage_event(text,text,timestamptz) from public,anon,authenticated;
revoke execute on function public.read_ante_core_founder_dashboard_monthly_actions(timestamptz) from public,anon,authenticated;
grant execute on function public.record_ante_core_usage_event(text,text,timestamptz) to service_role;
grant execute on function public.read_ante_core_founder_dashboard_monthly_actions(timestamptz) to service_role;
